version: '2.4'
services:
  redis:
    image: redis:7.0.5
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/store/dbs/redis/data:/data"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server

