version: '2.4'
services:
  phpmyadmin:
    image: phpmyadmin:5.2.1
    environment:
      - PMA_HOST=mysqldb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=1234
    restart: always
    ports:
      - "8082:80"

